### ISSUE TITLE
Crash issue on clicking "Extract"

### ISSUE THREAD

**Issue by FrankRicharrd** [gaoxifeng/robust_hex_dominant_meshing#1]
I had compiled your latest source and tried to run the application. Its getting crashed on clicking on "extract" button. I tried debugging, its showing an error as "vector<bool> dereferenced" and also some times shows "vector subscript out of range". Kindly fix this issue or give clue on how to fix it.
![2017-06-12_12h38_34](https://user-images.githubusercontent.com/22033367/27022475-c73deaa8-4f6b-11e7-9e8f-1d17237ed029.png)

**Comment by gaoxifeng** [comment]
From the unclear image, I guess that you didn't optimize posy.

**Comment by FrankRicharrd** [comment]
i tried that too. still facing the same issue.

Please use the below link to view the image.

Thanks.

[https://drive.google.com/file/d/0B64J0n_MNb34a0Y2RXNXU2JZRFU/view?usp=sharing]

https://drive.google.com/file/d/0B64J0n_MNb34a0Y2RXNXU2JZRFU/view?usp=sharing

**Comment by FrankRicharrd** [comment]
Now I had used your 25th revision. still its showing the exception.
[https://drive.google.com/file/d/0B64J0n_MNb34THJMajZSMkVJN0E/view?usp=sharing](url)

https://drive.google.com/file/d/0B64J0n_MNb34THJMajZSMkVJN0E/view?usp=sharing

**Comment by gaoxifeng** [comment]
Once you clicked the button for rosy, you have to wait for the optimization to be finished, the colour of the button will change. the same for other buttons.

**Comment by FrankRicharrd** [comment]
ok thanks a lot . i will try.

**Comment by FrankRicharrd** [comment]
thanks a lot. its working fine. 

https://drive.google.com/file/d/0B64J0n_MNb34MW5WSXpuaWM5NUk/view?usp=sharing
