### ISSUE TITLE
Execution problem

### ISSUE THREAD

**Issue by mfbfrance** [gaoxifeng/robust_hex_dominant_meshing#2]
Hi Mr. GAO,

I compile the source using Visual Studio 2017 (15.2) and just after I executed the file "robust_hex_dominant_meshing.exe" and just after start I'm getting: 
"GLFW error 65544: Vulkan: Failed to query instance extension count: A host memor
y allocation has failed
Error 00000501 after convex fill
Error 00000501 after convex fill
Error 00000501 after convex fill"

**Comment by mfbfrance** [comment]
Is it possible to your to sent your .exe file?

**Comment by gaoxifeng** [comment]
Reasons causing this issue may be because your graphics card driver doesn't support OpenGL 3.X.

**Comment by gaoxifeng** [comment]
Or when you run it on a remote windows 10 machine.

**Comment by mfbfrance** [comment]
my graphics card is a nvidia quadro M1000M and I'm using Windows 7. Should
I compile differently?

Regards
Marcelo

**Comment by gaoxifeng** [comment]
The error you reported is from GLFW, this typically means something wrong with the graphics card driver configuration for the program. You may want to try to run it on a different machine.
