### ISSUE TITLE
build error in linux 

### ISSUE THREAD

**Issue by idhamari** [gaoxifeng/robust_hex_dominant_meshing#4]
Thanks for sharing,
I tried to build the tool in my Linux machine and I get this error:

`
viewer.cpp: In constructor ‘Viewer::Viewer(std::__cxx11::string&, bool)’:
 /src/src/viewer.cpp:186:63: error: ‘Alignment’ is not a class, namespace, or enumeration
  statePanel->setLayout(new BoxLayout(Orientation::Horizontal, Alignment::Middle, 0, 5));

`

**Comment by gaoxifeng** [comment]
could you try the current version if it works now?
